//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSharpEssentialsAnalyzers {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CSharpEssentialsAnalyzers.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inject a new parameter in the constructor..
        /// </summary>
        internal static string CtorCodeFix {
            get {
                return ResourceManager.GetString("CtorCodeFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try to replace the hard depedency with constructor based dependency injection.
        /// </summary>
        internal static string CtorDescription {
            get {
                return ResourceManager.GetString("CtorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ry to replace the hard depedency with constructor based dependency injection.
        /// </summary>
        internal static string CtorMessageFormat {
            get {
                return ResourceManager.GetString("CtorMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Constructor Dependency Injection.
        /// </summary>
        internal static string CtorTitle {
            get {
                return ResourceManager.GetString("CtorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove catch block.
        /// </summary>
        internal static string EmptyCatchClause00CodeFixMessage {
            get {
                return ResourceManager.GetString("EmptyCatchClause00CodeFixMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove catch block and add comment.
        /// </summary>
        internal static string EmptyCatchClause01CodeFixMessage {
            get {
                return ResourceManager.GetString("EmptyCatchClause01CodeFixMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove catch block and braces.
        /// </summary>
        internal static string EmptyCatchClause02CodeFixMessage {
            get {
                return ResourceManager.GetString("EmptyCatchClause02CodeFixMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catch exception and rethrow.
        /// </summary>
        internal static string EmptyCatchClause03CodeFixMessage {
            get {
                return ResourceManager.GetString("EmptyCatchClause03CodeFixMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catch clause should not be empty.
        /// </summary>
        internal static string EmptyCatchClauseDescription {
            get {
                return ResourceManager.GetString("EmptyCatchClauseDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catch clause is empty.
        /// </summary>
        internal static string EmptyCatchClauseMessageFormat {
            get {
                return ResourceManager.GetString("EmptyCatchClauseMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catch clause is empty.
        /// </summary>
        internal static string EmptyCatchClauseTitle {
            get {
                return ResourceManager.GetString("EmptyCatchClauseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lines of code exceeds the presribed number of 25.
        /// </summary>
        internal static string MethodTooLongDescription {
            get {
                return ResourceManager.GetString("MethodTooLongDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lines of code exceeds the presribed number of 25.
        /// </summary>
        internal static string MethodTooLongMessageFormat {
            get {
                return ResourceManager.GetString("MethodTooLongMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method too long.
        /// </summary>
        internal static string MethodTooLongTitle {
            get {
                return ResourceManager.GetString("MethodTooLongTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add TODO comment of refactoring..
        /// </summary>
        internal static string MethodWithTooManyParametersCodeFix {
            get {
                return ResourceManager.GetString("MethodWithTooManyParametersCodeFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A method with more than 5 parameters is painful to call and might also degrade performance..
        /// </summary>
        internal static string MethodWithTooManyParametersDescription {
            get {
                return ResourceManager.GetString("MethodWithTooManyParametersDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method with too many parameters.
        /// </summary>
        internal static string MethodWithTooManyParametersMessageFormat {
            get {
                return ResourceManager.GetString("MethodWithTooManyParametersMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method with too many parameters - critical.
        /// </summary>
        internal static string MethodWithTooManyParametersTitle {
            get {
                return ResourceManager.GetString("MethodWithTooManyParametersTitle", resourceCulture);
            }
        }
    }
}
